server:
  port: 8080

spring:
  application:
    name: healthsure-backend
  data:
    mongodb:
      uri: mongodb://localhost:27017/healthsure
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379

jwt:
  secret: averylongsecretkeythathastobeatleast256bitslongforhs256algorithm
  expiration: 86400000 # 24 hours

cors:
  allowed-origins: "http://localhost:5173"
